info:
  name: redis-server
  component: Redis Application Server

spring:
  redis:
    host: 192.168.8.61
    port: 6379

center:
  server: 192.168.8.61:8003

server:
  port: ${port:1000}

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex'
  level:
    org.springframework: INFO
    cn.gtmap.landsale.redis: DEBUG